# Generated by Django 4.0.2 on 2022-02-16 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfetcherapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='image',
            field=models.ImageField(null=True, upload_to='source_logos/'),
        ),
    ]
