# Generated by Django 4.0.2 on 2022-02-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfetcherapp', '0002_source_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
