# Generated by Django 4.0.2 on 2022-02-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfetcherapp', '0003_alter_source_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='assigned_to_user_by_default',
            field=models.BooleanField(default=False),
        ),
    ]
