# Generated by Django 4.0.2 on 2022-02-18 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainfetcherapp', '0004_source_assigned_to_user_by_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField(unique=True)),
                ('html', models.TextField()),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('summary', models.TextField()),
                ('main_image', models.TextField()),
                ('publish_date', models.TextField()),
                ('download_date', models.DateTimeField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfetcherapp.source')),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationServing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_date', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.TextField()),
                ('topic_description', models.TextField()),
                ('topic_method', models.IntegerField()),
                ('recommendation_serving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfetcherapp.recommendationserving')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfetcherapp.article')),
                ('recommendation_serving', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfetcherapp.recommendationserving')),
                ('topic_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainfetcherapp.recommendationtopic')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluatedArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_already_downloaded', models.BooleanField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainfetcherapp.article')),
            ],
        ),
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=15)),
                ('lemmatized', models.CharField(max_length=15)),
                ('block_all_occurences', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
