# Generated by Django 4.0.2 on 2022-02-18 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfetcherapp', '0005_article_recommendationserving_recommendationtopic_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EvaluatedArticle',
            new_name='CurrentlyEvaluatedArticle',
        ),
    ]
