# Generated by Django 4.0.2 on 2022-02-18 18:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainfetcherapp', '0006_rename_evaluatedarticle_currentlyevaluatedarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentlyFetchedForUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
