# Generated by Django 4.0.2 on 2022-02-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainfetcherapp', '0007_currentlyfetchedforuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationserving',
            name='ready_for_users',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
