# Generated by Django 4.0.2 on 2022-02-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfetcherapp', '0010_rename_currentlyfetchedforuser_userbeingfetchedfor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CurrentlyEvaluatedArticle',
            new_name='CurrentlyFetchedArticle',
        ),
    ]
