# Generated by Django 4.0.2 on 2022-02-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainfetcherapp', '0011_rename_currentlyevaluatedarticle_currentlyfetchedarticle'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Recommendations',
            new_name='Recommendation',
        ),
    ]
