# Generated by Django 4.0.2 on 2022-02-21 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainfetcherapp', '0012_rename_recommendations_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleKeyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('lemmatized_text', models.TextField()),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mainfetcherapp.article')),
            ],
        ),
    ]
