# Generated by Django 4.0.2 on 2022-02-21 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainfetcherapp', '0013_articlekeyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlekeyword',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainfetcherapp.article'),
        ),
    ]
